module.exports = {
    "person": "🙅‍♂️",
    "bicycle": "🚲",
    "car": "🚗",
    "motorcycle": "🏍",
    "airplane": "✈️",
    "bus": "🚌",
    "train": "🚂",
    "truck": "🚚",
    "boat": "⛵",
    "traffic light": "🚦",
    "fire hydrant": "🚒",
    "stop sign": "🛑",
    "parking meter": "🅿️",
    "bench": "🪑",
    "bird": "🐦",
    "cat": "🐈",
    "dog": "🐕",
    "horse": "🐎",
    "sheep": "🐏",
    "cow": "🐄",
    "elephant": "🐘",
    "bear": "🐻",
    "zebra": "🦓",
    "giraffe": "🦒",
    "backpack": "🎒",
    "umbrella": "☂️",
    "handbag": "👜",
    "tie": "👔",
    "suitcase": "🧳",
    "frisbee": "🥏",
    "skis": "🎿",
    "snowboard": "🏂",
    "sports ball": "⚽",
    "kite": "🪁",
    "skateboard": "🛹",
    "surfboard": "🏄",
    "tennis racket": "🎾",
    "bottle": "🍼",
    "wine glass": "🍷",
    "cup": "☕",
    "fork": "🍴",
    "knife": "🔪",
    "spoon": "🥄",
    "bowl": "🍲",
    "banana": "🍌",
    "apple": "🍏",
    "sandwich": "🥪",
    "orange": "🍊",
    "broccoli": "🥦",
    "carrot": "🥕",
    "hot dog": "🌭",
    "pizza": "🍕",
    "donut": "🍩",
    "cake": "🍰",
    "chair": "🪑",
    "couch": "🛋",
    "potted plant": "🪴",
    "bed": "🛏",
    "toilet": "🚽",
    "tv": "📺",
    "laptop": "💻",
    "mouse": "🖱",
    "remote": "📱",
    "keyboard": "⌨️",
    "cell phone": "📱",
    "microwave": "🌊",
    "toaster": "🍞",
    "refrigerator": "🍽",
    "book": "📚",
    "clock": "⏰",
    "vase": "🏺",
    "scissors": "✂️",
    "teddy bear": "🧸",
    "hair drier": "💨",
    "toothbrush": "🪥",
    "baseball bat": "🏏",
    "baseball glove": "🥅",
    "dining table": "🍽",
    "oven": "🔥",
    "sink": "🚰",
    "Clock Format": "⏲",
    "_default": "🏃‍♂️"
}
